add support for `default_version` in control file
supabase/dbdev pull request #153
Opened 2023-12-05 14:16 UTC by imor

## What kind of change does this PR introduce?

feature

## What is the current behavior?

`default_version` key in the control file is not sent to the backend when a user runs `dbdev publish`. This results in TLE's default version being the first installed version which is usually the oldest version.

## What is the new behavior?

The `default_version` is now tracked in the `app.packages` table in the `default_version_struct` and `default_version` columns. The `dbdev` CLI also sends the `default_version` from the control file to the backend when running `dbdev publish` command. The CLI also checks that the `default_version` in the control file is one of the valid versions of the package. The in-db client has been updated to fetch the `default_version` from the `public.packages` view and call the `pgtle.set_default_version` function.

Because old dbdev CLI versions are not aware of `default_version`, the `default_version_struct` and `default_version` columns in `app.packages` are nullable for backward compatibility with those older CLI versions.

## Additional context

Fixes #147

2024-01-02 14:52 UTC, olirice requested changes
> Because old dbdev CLI versions are not aware of default_version, the default_version_struct and default_version columns in app.packages are nullable for backward compatibility with those older CLI versions.

The current user base is like 5 people and we're pre-1.0. I think it's worth taking a breaking change thats solvable with a CLI upgrade to avoid having to make the field nullable at this point. wdyt?

2024-01-03 10:29 UTC, imor commented
> > Because old dbdev CLI versions are not aware of default_version, the default_version_struct and default_version columns in app.packages are nullable for backward compatibility with those older CLI versions.
> 
> The current user base is like 5 people and we're pre-1.0. I think it's worth taking a breaking change thats solvable with a CLI upgrade to avoid having to make the field nullable at this point. wdyt?

`default_version` is important to be set so making it non-nullable definitely reduces chances of bugs with the added benefit of making the code in this PR a lot simpler. So let me make this change.

2024-01-03 12:03 UTC, imor commented on supabase/migrations/20231205051816_add_default_version.sql
> +add column default_version_struct app.semver not null default app.text_to_semver('0.0.0'),
`default_version_struct` is not longer nullable.

2024-01-03 12:04 UTC, imor commented on supabase/migrations/20231205051816_add_default_version.sql
> +    end if;
If the client doesn't send `default_version` we hint in the error message for older clients to be upgraded to the latest.

2024-01-03 16:16 UTC, merged